### ISSUE TITLE
No module named "multimodal.commands"

### ISSUE THREAD

**Issue by chxw20** [cdancette/multimodal#18]
I am trying to use multimodal with python3.7. When calling the command
```python -m multimodal vqa2-eval -p /path/to/pred.json --split val```
it says `ModuleNotFoundError: No module named 'multimodal.commands'`. It seems there is no "commands" folder contained in the src code.

**Comment by cdancette** [comment]
Thanks for the report, I'll look into this !

**Comment by cdancette** [comment]
@chxw20 I just uploaded an update, please let me know if it fixed the issue.
